name: muslim_werd_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Flutter packages
dependencies:
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.6
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  icons_launcher: ^3.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# Generate Logo App
icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# Generate images_app.dart file
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/theming/
  filename: assets.dart
  field_prefix: ""
  ignore_comments: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf

    - family: UthmanTN1
      fonts:
        - asset: assets/fonts/UthmanTN1-Ver10.otf
